[package]
name = "threemonthsofrust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "day1_ownership"
path = "days/day1/ownership.rs"

[[bin]]
name = "day1_functions"
path = "days/day1/functions.rs"
